openapi: 3.0.1
info:
  title: Cybertruck API
  description: Cybertruck API
  contact:
    name: Daham
    url: ''
    email: dahampositha33@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
  x-api-id: location-api
servers:
  - url: /
    description: Local Server
paths:
  /health:
    get:
      tags:
        - health-check-controller
      operationId: health
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HealthComponent'
  /health/status:
    get:
      tags:
        - health-check-controller
      operationId: status
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    HealthComponent:
      type: object
      properties:
        description:
          type: string
        status:
          type: string
    Status:
      type: object
      properties:
        description:
          type: string
        status:
          type: string
