openapi: 3.0.1
info:
  title: cybertruck-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /products:
    post:
      tags:
        - product-controller
      summary: Create a product
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequestDto'
        required: true
      responses:
        '201':
          description: Successfully created a product
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductCreateResponseDto'
  /orders:
    post:
      tags:
        - order-controller
      summary: Create an order
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequestDto'
        required: true
      responses:
        '201':
          description: Successfully created an order
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderCreateResponseDto'
  /customers:
    post:
      tags:
        - customer-controller
      summary: Create a customer
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreateRequestDto'
        required: true
      responses:
        '201':
          description: Successfully created a customer
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomerCreateResponseDto'
  /health:
    get:
      tags:
        - health-check-controller
      operationId: health
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HealthComponent'
  /health/status:
    get:
      tags:
        - health-check-controller
      operationId: status
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    ProductCreateRequestDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
      description: Product to create. Cannot null or empty.
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        address:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int32
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        customer:
          $ref: '#/components/schemas/Customer'
        orderDate:
          type: string
          format: date-time
        totalAmount:
          type: number
          format: double
    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
        order:
          $ref: '#/components/schemas/Order'
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
          format: int32
        unitPrice:
          type: number
          format: double
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    ProductCreateResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderCreateRequestDto:
      type: object
      properties:
        customer_id:
          type: integer
          format: int32
        order_date:
          type: string
          format: date-time
      description: Order to create. Cannot null or empty.
    OrderCreateResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        customer_id:
          type: integer
          format: int32
        order_date:
          type: string
          format: date-time
        total_amount:
          type: number
          format: double
    CustomerCreateRequestDto:
      type: object
      properties:
        email:
          type: string
        address:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        phone_number:
          type: string
      description: Customer to create. Cannot null or empty.
    CustomerCreateResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        email:
          type: string
        address:
          type: string
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        first_name:
          type: string
        last_name:
          type: string
        phone_number:
          type: string
    HealthComponent:
      type: object
      properties:
        description:
          type: string
        status:
          type: string
    Status:
      type: object
      properties:
        description:
          type: string
        status:
          type: string
