openapi: 3.0.1
info:
  title: cybertruck-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      tags:
        - health-check-controller
      operationId: health
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HealthComponent'
  /health/status:
    get:
      tags:
        - health-check-controller
      operationId: status
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    HealthComponent:
      type: object
      properties:
        description:
          type: string
        status:
          type: string
    Status:
      type: object
      properties:
        description:
          type: string
        status:
          type: string
